# Generated by Django 2.1.1 on 2019-01-24 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('sign_up_date', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('house_number', models.CharField(blank=True, max_length=128, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('barangay', models.CharField(blank=True, max_length=128, null=True)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('city_municipality', models.CharField(blank=True, max_length=128, null=True)),
                ('province', models.CharField(blank=True, max_length=128, null=True)),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('email_address', models.CharField(blank=True, max_length=128, null=True)),
                ('fb_account', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=128, null=True)),
                ('nationality', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, max_length=128, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=128, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=128, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place_city_municipality', models.CharField(blank=True, max_length=128, null=True)),
                ('birth_place_province', models.CharField(blank=True, max_length=128, null=True)),
                ('birth_place_region', models.CharField(blank=True, max_length=128, null=True)),
                ('educational_attainment', models.CharField(blank=True, max_length=128, null=True)),
                ('client_classification', models.CharField(blank=True, max_length=128, null=True)),
                ('has_taken', models.BooleanField(default=False)),
                ('taken_this_where', models.CharField(blank=True, max_length=128, null=True)),
                ('taken_this_when', models.DateField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applicantinformation',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctti_webapp.UserExt'),
        ),
    ]
