# Generated by Django 2.1.1 on 2019-01-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctti_webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantinformation',
            old_name='house_number',
            new_name='house_number_street',
        ),
        migrations.RemoveField(
            model_name='applicantinformation',
            name='street',
        ),
    ]
