# Generated by Django 2.1.4 on 2019-02-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctti_webapp', '0002_auto_20190129_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantinformation',
            name='applicant',
        ),
    ]
