# Generated by Django 2.1.4 on 2019-02-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctti_webapp', '0004_applicantinformation_reference_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantinformation',
            old_name='email_address',
            new_name='email_address_or_fb',
        ),
        migrations.RemoveField(
            model_name='applicantinformation',
            name='fb_account',
        ),
    ]
