# Generated by Django 2.1.4 on 2019-02-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctti_webapp', '0005_auto_20190203_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinformation',
            name='birth_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
