# Generated by Django 2.1.4 on 2019-02-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctti_webapp', '0006_auto_20190203_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinformation',
            name='birth_date',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
