# Generated by Django 2.1.4 on 2019-02-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctti_webapp', '0007_auto_20190203_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinformation',
            name='taken_this_when',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
