# Generated by Django 2.1.4 on 2019-02-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctti_webapp', '0008_auto_20190203_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantinformation',
            name='lrn',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
