# Generated by Django 2.1.1 on 2019-02-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctti_webapp', '0009_applicantinformation_lrn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantinformation',
            old_name='lrn',
            new_name='unified_learner_id',
        ),
        migrations.AddField(
            model_name='applicantinformation',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
